name: Deploy Static Site to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Upload files to Azure Static Website
        run: |
         
            az storage blob upload-batch \
              --account-name nanaportstorageaccount1\
              --destination '$web' \
              --source ./my_portfolio \
              -- auth-mode login \
              --overwrite

            echo "deployment completed!"
